#!/usr/bin/python3
import argparse
import sys

from argo_probe_keycloak.keycloak import fetch_keycloak_token


def main():
    parser = argparse.ArgumentParser(
        description='Nagios probe for Keycloak login'
    )
    parser.add_argument(
        "--token_endpoint", dest="endpoint", type=str, required=True,
        help="The token endpoint"
    )
    parser.add_argument(
        "--client_id", dest="client_id", type=str, required=True,
        help="The identifier of the client"
    )
    parser.add_argument(
        "--client_secret", dest="client_secret", type=str, required=True,
        help="The secret value of the client"
    )
    parser.add_argument(
        "-t", "--timeout", dest="timeout", type=int, default=60,
        help="timeout"
    )
    args = parser.parse_args()

    status = fetch_keycloak_token(args)

    print(status["message"])
    sys.exit(status["code"])


if __name__ == '__main__':
    main()
